require:
  - rubocop-rspec
  
AllCops:
  Include:
    - "**/*.rb"
  NewCops: enable

Style/StringLiterals:
  Enabled: true

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Layout/LineLength:
  Enabled: false

# Configurações para o diretório /spec
RSpec:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups: 
  Enabled: false
